spring.application.name=spring-prototype

# PROD Services
#There is also an /actuator/shutdown endpoint, but, by default, it is visible only through JMX. To enable it as an HTTP endpoint
management.endpoint.shutdown.enabled=true
#To expose it:
#Note: probably should not enable the shutdown endpoint for a publicly available application.
management.endpoints.web.exposure.include=health,info,shutdown

#Integrate: https://spring.io/guides/gs/serving-web-content